//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parking_servisEntities1 : DbContext
    {
        public parking_servisEntities1()
            : base("name=parking_servisEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cene> cenes { get; set; }
        public virtual DbSet<korisnik> korisniks { get; set; }
        public virtual DbSet<parkingmesto> parkingmestoes { get; set; }
    }
}
